'use client'

export type Lang = 'en' | 'es'

export const translations = {
  en: {
    appName: 'Cruza',
    subtitle: 'Wait times entering the US from Mexico',
    allRegions: '📍 All Regions',
    enteringUS: '🇺🇸 Entering the US',
    enteringMexico: '🇲🇽 Entering Mexico',
    updatedJustNow: 'Updated just now',
    updatedAgo: (m: number) => `Updated ${m}m ago`,
    list: 'List',
    map: 'Map',
    tapDot: 'Tap a dot to see details',
    noData: 'No port data available.',
    car: 'Car',
    sentri: 'SENTRI',
    walk: 'Walk',
    truck: 'Truck',
    carsAhead: (n: number) => `~${n} cars`,
    closed: 'Closed',
    signUpFree: 'Sign Up Free',
    localBusiness: 'Local business?',
    me: 'Me',
    underMin: 'Under 20 min',
    midMin: '20–45 min',
    overMin: '45+ min',
    mexicoSideTitle: 'Mexico-side wait times',
    mexicoSideDesc: 'No official data exists for crossing into Mexico — Mexico doesn\'t publish wait times publicly. Wait times entering Mexico are typically under 5 minutes.',
    communityTip: '💡 Community tip',
    communityTipDesc: 'Returning to Mexico is usually quick — Mexican customs rarely causes delays. Busy periods are Friday afternoons and weekends when US-side shoppers return.',
    createAccount: 'Create a free account',
    toSeeLocalDeals: 'to see local deals instead of ads',
  },
  es: {
    appName: 'Cruza',
    subtitle: 'Tiempos de espera para entrar a EE.UU. desde México',
    allRegions: '📍 Todas las regiones',
    enteringUS: '🇺🇸 Entrando a EE.UU.',
    enteringMexico: '🇲🇽 Entrando a México',
    updatedJustNow: 'Actualizado ahora mismo',
    updatedAgo: (m: number) => `Actualizado hace ${m} min`,
    list: 'Lista',
    map: 'Mapa',
    tapDot: 'Toca un punto para ver detalles',
    noData: 'No hay datos disponibles.',
    car: 'Auto',
    sentri: 'SENTRI',
    walk: 'Peatón',
    truck: 'Camión',
    carsAhead: (n: number) => `~${n} autos`,
    closed: 'Cerrado',
    signUpFree: 'Regístrate Gratis',
    localBusiness: '¿Negocio local?',
    me: 'Yo',
    underMin: 'Menos de 20 min',
    midMin: '20–45 min',
    overMin: '45+ min',
    mexicoSideTitle: 'Tiempos del lado mexicano',
    mexicoSideDesc: 'No existen datos oficiales para cruzar a México — México no publica tiempos de espera. Entrar a México generalmente toma menos de 5 minutos.',
    communityTip: '💡 Consejo de la comunidad',
    communityTipDesc: 'Regresar a México suele ser rápido. Los períodos más ocupados son los viernes por la tarde y los fines de semana cuando los compradores regresan.',
    createAccount: 'Crea una cuenta gratis',
    toSeeLocalDeals: 'para ver ofertas locales en vez de anuncios',
  },
}

export type T = typeof translations.en
